In [16]:
import pandas as pd
import numpy as np

# Example: Using .loc[] and .iloc[]

In [17]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [24, 27, 22, 32],
        'Score': [85, 92, 88, 76]}

df = pd.DataFrame(data)

df

      Name  Age  Score
0    Alice   24     85
1      Bob   27     92
2  Charlie   22     88
3    David   32     76

In [18]:
# Select the 'Name' column
print(df['Name'])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object

In [19]:
# Select rows and specific columns
print(df.loc[0:2, ['Name', 'Age']])

#inclusive of the 2

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

In [20]:
# Select rows by position
print(df.iloc[:2])  # First two rows

# up to row 2 but not including it (so we grab rows 0 and 1)

    Name  Age  Score
0  Alice   24     85
1    Bob   27     92

In [21]:
print(df.loc[0:2])  # This prints the first 3 rows! It starts with the row with index 0 and continues up to and including the row with index 2.

print(df.iloc[:2]) # This prints the first 2 rows only.  iloc[] works like list slicing.  It does not include the row with index 2.

print(df.loc[[0,2]]) # This prints row 0 and row 2.  You specify a list of the rows you want.  You can't do this with lists!

      Name  Age  Score
0    Alice   24     85
1      Bob   27     92
2  Charlie   22     88
    Name  Age  Score
0  Alice   24     85
1    Bob   27     92
      Name  Age  Score
0    Alice   24     85
2  Charlie   22     88

## can also do filters

In [22]:
print(df[df['Age'] > 24])

    Name  Age  Score
1    Bob   27     92
3  David   32     76

In [23]:
#print(df[df['Age'] > 24 and df['Score'] >=88])         #Doesn't work!  'and' is not a valid operator for Series!
print(df[(df['Age'] > 24) & (df['Score'] >=88)])        # This one does work! It does the boolean AND of corresponding series elements.

  Name  Age  Score
1  Bob   27     92

In [24]:
# print(df["a" in df['Name']])                          Doesn't work!  The "in" operator doesn't work for Series!
print(df[df['Name'].str.contains("a")])                 # This does work!

      Name  Age  Score
2  Charlie   22     88
3    David   32     76

In [25]:
# There are a bunch of useful str functions for Series. 
# df['Name'] = df['Name'].upper()                       Doesn't work!!

df['Name'] = df['Name'].str.upper()                     # Does work! 
print(df)

      Name  Age  Score
0    ALICE   24     85
1      BOB   27     92
2  CHARLIE   22     88
3    DAVID   32     76

In [26]:
import pandas as pd
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [23, 27, 32, 44]}
df = pd.DataFrame(data)

# Slice 1
subset_loc = df.loc[0:2, ['Name']]
# Slice 2
subset_iloc = df.iloc[0:2, ]

In [27]:
subset_loc #will print alice, bob, charlie

      Name
0    Alice
1      Bob
2  Charlie

In [28]:
subset_iloc #will print the first two rows of alice and bob with name and age

    Name  Age
0  Alice   23
1    Bob   27

# Data Aggregation

## basics

In [29]:
data = {'Category': ['A', 'B', 'A', 'B', 'C'],
        'Values': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

df

  Category  Values
0        A      10
1        B      20
2        A      30
3        B      40
4        C      50

In [30]:
# Group by 'Category' and calculate the sum
grouped = df.groupby('Category').sum()
print(grouped) # grouped is another DataFrame with summary data

# Calculate the mean for each group
# can do either code
#mean_values = df.groupby('Category')['Values'].mean()
mean_values2 = df.groupby('Category').mean() 
print(mean_values2)

          Values
Category
A             40
B             60
C             50
          Values
Category
A           20.0
B           30.0
C           50.0

## advanced (doing multiple aggregations at once)

In [31]:
data = {'Category': ['A', 'B', 'A', 'B', 'C'],
        'Values': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

df

  Category  Values
0        A      10
1        B      20
2        A      30
3        B      40
4        C      50

In [32]:
# Group by 'Category' and apply multiple aggregation functions
result = df.groupby('Category').agg({'Values': ['sum', 'mean', 'count']})
print(result)

         Values
            sum  mean count
Category
A            40  20.0     2
B            60  30.0     2
C            50  50.0     1

In [33]:
result1 = df.groupby('Category').agg({'Values': 'sum'})
result1

          Values
Category
A             40
B             60
C             50

In [34]:
result2 = df.groupby('Category').agg({'Values': ['sum', 'mean', 'count']})
result2

         Values
            sum  mean count
Category
A            40  20.0     2
B            60  30.0     2
C            50  50.0     1

# Pivot Tables

In [35]:
data = [{'Employee': 'Jones', 'Product': 'Widget', 'Region': 'West', 'Revenue': 9000}, \
{'Employee': 'Jones', 'Product': 'Gizmo', 'Region': 'West', 'Revenue': 4000}, \
{'Employee': 'Jones', 'Product': 'Doohickey', 'Region': 'West', 'Revenue': 11000}, \
{'Employee': 'Jones', 'Product': 'Widget', 'Region': 'East', 'Revenue': 4000}, \
{'Employee': 'Jones', 'Product': 'Gizmo', 'Region': 'East', 'Revenue': 5500}, \
{'Employee': 'Jones', 'Product': 'Doohickey', 'Region': 'East', 'Revenue': 2345}, \
{'Employee': 'Smith', 'Product': 'Widget', 'Region': 'West', 'Revenue': 9007}, \
{'Employee': 'Smith', 'Product': 'Gizmo', 'Region': 'West', 'Revenue': 40003}, \
{'Employee': 'Smith', 'Product': 'Doohickey', 'Region': 'West', 'Revenue': 110012}, \
{'Employee': 'Smith', 'Product': 'Widget', 'Region': 'East', 'Revenue': 9002}, \
{'Employee': 'Smith', 'Product': 'Gizmo', 'Region': 'East', 'Revenue': 15500}, \
{'Employee': 'Garcia', 'Product': 'Widget', 'Region': 'West', 'Revenue': 6007}, \
{'Employee': 'Garcia', 'Product': 'Gizmo', 'Region': 'West', 'Revenue': 42003}, \
{'Employee': 'Garcia', 'Product': 'Doohickey', 'Region': 'West', 'Revenue': 160012}, \
{'Employee': 'Garcia', 'Product': 'Gizmo', 'Region': 'East', 'Revenue': 16500}, \
{'Employee': 'Garcia', 'Product': 'Doohickey', 'Region': 'East', 'Revenue': 2458}]

sales = pd.DataFrame(data)

sales

   Employee    Product Region  Revenue
0     Jones     Widget   West     9000
1     Jones      Gizmo   West     4000
2     Jones  Doohickey   West    11000
3     Jones     Widget   East     4000
4     Jones      Gizmo   East     5500
5     Jones  Doohickey   East     2345
6     Smith     Widget   West     9007
7     Smith      Gizmo   West    40003
8     Smith  Doohickey   West   110012
9     Smith     Widget   East     9002
10    Smith      Gizmo   East    15500
11   Garcia     Widget   West     6007
12   Garcia      Gizmo   West    42003
13   Garcia  Doohickey   West   160012
14   Garcia      Gizmo   East    16500
15   Garcia  Doohickey   East     2458

In [36]:
sales_pivot1 = pd.pivot_table(sales,index=['Product','Region'],values=['Revenue'],aggfunc='sum',fill_value=0)

sales_pivot1
# This creates a two level index to show sales by product and region. The revenue values are summed for each product and region.

                  Revenue
Product   Region
Doohickey East       4803
          West     281024
Gizmo     East      37500
          West      86006
Widget    East      13002
          West      24014

In [37]:
sales_pivot2 = pd.pivot_table(sales,index='Product',values='Revenue',columns='Region', aggfunc='sum',fill_value=0)
sales_pivot2
# The result here is similar, but instead of a two level index, you have columns to give sales by region.

Region      East    West
Product
Doohickey   4803  281024
Gizmo      37500   86006
Widget     13002   24014

In [38]:
sales_pivot3 = pd.pivot_table(sales,index='Product',values='Revenue',columns=['Region','Employee'], aggfunc='sum',fill_value=0)
sales_pivot3
# By adding the employee column, you get these revenue numbers broken down by employee.  The fill value is used when there is no corresponding entry.


# sales_pivot3.columns #print what the columns are

Region      East                 West
Employee  Garcia Jones  Smith  Garcia  Jones   Smith
Product
Doohickey   2458  2345      0  160012  11000  110012
Gizmo      16500  5500  15500   42003   4000   40003
Widget         0  4000   9002    6007   9000    9007

# Merging and Joining

## merge
- based on columns that are present in both dataframes

In [39]:
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Score': [85, 92, 88]})

print(df1)
df2

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

   ID  Score
0   1     85
1   2     92
2   4     88

In [40]:
# Merge on the 'ID' column
merged_df = pd.merge(df1, df2, on='ID', how='inner') #inner merge
merged_df

   ID   Name  Score
0   1  Alice     85
1   2    Bob     92

### merge on multiple columns

In [41]:
df1 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Date': ['2021-01-01', '2021-01-02', '2021-01-03'],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': [1, 2, 3],
    'Date': ['2021-01-01', '2021-01-02', '2021-01-03'],
    'Score': [85, 92, 88]
})

print(df1)
df2

   ID        Date     Name
0   1  2021-01-01    Alice
1   2  2021-01-02      Bob
2   3  2021-01-03  Charlie

   ID        Date  Score
0   1  2021-01-01     85
1   2  2021-01-02     92
2   3  2021-01-03     88

In [42]:
merged_df = pd.merge(df1, df2, on=['ID', 'Date'], how='inner')
merged_df

   ID        Date     Name  Score
0   1  2021-01-01    Alice     85
1   2  2021-01-02      Bob     92
2   3  2021-01-03  Charlie     88

## join

- based on indexes

In [43]:
df1 = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
df2 = pd.DataFrame({'Score': [85, 92, 88]}, index=[1, 2, 4])

print(df1)
df2

      Name
1    Alice
2      Bob
3  Charlie

   Score
1     85
2     92
4     88

In [44]:
joined_df = df1.join(df2, how='outer')
joined_df

      Name  Score
1    Alice   85.0
2      Bob   92.0
3  Charlie    NaN
4      NaN   88.0

# data transformation
- adding, replace, deleting columns of a dataframe at any time

In [45]:
joined_df['bogus']= ['x','y','z','w'] # adds a column
joined_df

      Name  Score bogus
1    Alice   85.0     x
2      Bob   92.0     y
3  Charlie    NaN     z
4      NaN   88.0     w

In [46]:
joined_df['bogus'] = joined_df['bogus'] + "_value"  # replaces a column
joined_df

      Name  Score    bogus
1    Alice   85.0  x_value
2      Bob   92.0  y_value
3  Charlie    NaN  z_value
4      NaN   88.0  w_value

In [47]:
joined_df.drop('bogus', axis=1, inplace=True) # deletes the column.  You need axis=1 to identify that the drop is for a column, not a row
joined_df

      Name  Score
1    Alice   85.0
2      Bob   92.0
3  Charlie    NaN
4      NaN   88.0

## different ways to transform a series

In [48]:
data = {'Name': ['A','B','C'],'Value':[1,2,3]}
new_df = pd.DataFrame(data)

new_df

  Name  Value
0    A      1
1    B      2
2    C      3

In [49]:
new_df['Value'] = new_df['Value'] ** 2  # using an operator
new_df

  Name  Value
0    A      1
1    B      4
2    C      9

In [50]:
new_df['Value'] = np.sqrt(new_df['Value']) # using a numpy function.  You can't use math.sqrt() on a Series.
new_df

  Name  Value
0    A    1.0
1    B    2.0
2    C    3.0

In [51]:
new_df['EvenOdd'] = new_df['Value'].map(lambda x : 'Even' if x % 2 == 0 else 'Odd') # the map method for a Series
new_df

  Name  Value EvenOdd
0    A    1.0     Odd
1    B    2.0    Even
2    C    3.0     Odd

In [52]:
new_df['Value'] = new_df['Value'].astype(int) # type conversion method for a Series
new_df

  Name  Value EvenOdd
0    A      1     Odd
1    B      2    Even
2    C      3     Odd

# using the apply method

In [53]:
sales_pivot2['Total'] = sales_pivot2['East'] + sales_pivot2['West'] # adding two columns to make a new one
sales_pivot2

Region      East    West   Total
Product
Doohickey   4803  281024  285827
Gizmo      37500   86006  123506
Widget     13002   24014   37016

In [54]:
sales

   Employee    Product Region  Revenue
0     Jones     Widget   West     9000
1     Jones      Gizmo   West     4000
2     Jones  Doohickey   West    11000
3     Jones     Widget   East     4000
4     Jones      Gizmo   East     5500
5     Jones  Doohickey   East     2345
6     Smith     Widget   West     9007
7     Smith      Gizmo   West    40003
8     Smith  Doohickey   West   110012
9     Smith     Widget   East     9002
10    Smith      Gizmo   East    15500
11   Garcia     Widget   West     6007
12   Garcia      Gizmo   West    42003
13   Garcia  Doohickey   West   160012
14   Garcia      Gizmo   East    16500
15   Garcia  Doohickey   East     2458

### first example

In [55]:
per_employee_sales=sales.groupby('Employee').agg({'Revenue':'sum'}) #first
per_employee_sales

          Revenue
Employee
Garcia     226980
Jones       35845
Smith      183524

In [56]:
per_employee_sales['Commission Percentage'] = [0.12, 0.09, 0.1] #second
per_employee_sales

          Revenue  Commission Percentage
Employee
Garcia     226980                   0.12
Jones       35845                   0.09
Smith      183524                   0.10

In [57]:
per_employee_sales['Commission'] = per_employee_sales['Revenue'] * per_employee_sales['Commission Percentage'] #third

per_employee_sales #and complete after 3 lines of code

          Revenue  Commission Percentage  Commission
Employee
Garcia     226980                   0.12    27237.60
Jones       35845                   0.09     3226.05
Smith      183524                   0.10    18352.40

### second example (more complex)

In [58]:
per_employee_sales=sales.groupby('Employee').agg({'Revenue':'sum'})
per_employee_sales['Commission Plan'] = ['A', 'A', 'B']

per_employee_sales

          Revenue Commission Plan
Employee
Garcia     226980               A
Jones       35845               A
Smith      183524               B

- Sales employees on commission plan A get $1000 for the first 10000 in revenue, and 5% for revenue over 10000.  
- Everyone else gets $1400 for the first 10000 in revenue, but 4% for revenue over 10000.  
- All employees get zip (nothing or $0) if they don't get at least 10000 in revenue. 

You use apply(), and you specify axis=1 to request the entire row.  You pass a function to apply(), and the function is called once per row.  As follows:

In [59]:
def calculate_commission(row):
    if row['Revenue'] < 10000:
        return 0
    if row['Commission Plan'] == 'A':
        return 1000 + 0.05 * (row['Revenue'] - 10000)
    else:
        return 1400 + 0.04 * (row['Revenue'] - 10000)

per_employee_sales['Commission'] = per_employee_sales.apply(calculate_commission, axis=1)

per_employee_sales

          Revenue Commission Plan  Commission
Employee
Garcia     226980               A    11849.00
Jones       35845               A     2292.25
Smith      183524               B     8340.96

# utility methods

### changing column names

In [60]:
joined_df #before

      Name  Score
1    Alice   85.0
2      Bob   92.0
3  Charlie    NaN
4      NaN   88.0

In [ ]:
joined_df.rename(columns={'Score':'Test Score'}, inplace=True) #after
joined_df

      Name  Test Score
1    Alice        85.0
2      Bob        92.0
3  Charlie         NaN
4      NaN        88.0

### converting column to an index

In [62]:
joined_df #before

      Name  Test Score
1    Alice        85.0
2      Bob        92.0
3  Charlie         NaN
4      NaN        88.0

In [63]:
renamed_df=joined_df.set_index('Name')

renamed_df

         Test Score
Name
Alice          85.0
Bob            92.0
Charlie         NaN
NaN            88.0

### sorting

In [64]:
joined_df.sort_values(by='Test Score',ascending=False,inplace=True)
joined_df

      Name  Test Score
2      Bob        92.0
4      NaN        88.0
1    Alice        85.0
3  Charlie         NaN

- notice that after sorting the index, the index values are no longer in order 
- with this case and others, we should reset the index

In [65]:
joined_df.reset_index(inplace=True, drop=True)

joined_df

      Name  Test Score
0      Bob        92.0
1      NaN        88.0
2    Alice        85.0
3  Charlie         NaN

# categorical encoding

In [66]:
data = {'Color': ['Red', 'Blue', 'Green', 'Blue', 'Red']}
df = pd.DataFrame(data)

df

   Color
0    Red
1   Blue
2  Green
3   Blue
4    Red

### label encoding
- convert categories to numbers

In [67]:

df['Color_Label'] = df['Color'].map({'Red': 1, 'Blue': 2, 'Green': 3})

df

   Color  Color_Label
0    Red            1
1   Blue            2
2  Green            3
3   Blue            2
4    Red            1

### one hot encoding
- create binary columns for each category

In [68]:
df_encoded = pd.get_dummies(df['Color'], prefix='Color')

df_encoded

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3        True        False      False
4       False        False       True

# feature engineering

In [69]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Location': ['LA', 'LA', 'NY'],
        'Grade': [78, 40, 85]}
df = pd.DataFrame(data)

df

      Name Location  Grade
0    Alice       LA     78
1      Bob       LA     40
2  Charlie       NY     85

In [ ]:
# Convert grade into three categories, "bad", "okay", "great"

df['Grade'] = pd.cut(df['Grade'], 3, labels = ["bad", "okay", "great"])
df


# look up cut methods in panda

      Name Location  Grade
0    Alice       LA  great
1      Bob       LA    bad
2  Charlie       NY  great